name: Docker Image CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Set up Docker Buildx (required for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # Build the Docker image with a unique timestamp tag
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/my-vite-app:$(date +%s)
      # Push the Docker image to GHCR
      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.actor }}/my-vite-app:$(date +%s)
